settings:
  name: Settings
  view: yes
  icon: mdi:settings
  entities:
    - group.all_automations
    - group.network
    - group.system
    - group.dashboards

network:
  name: Network
  entities:
    - sensor.fritz_netmonitor
    - sensor.dsl_upload_speed
    - sensor.dsl_download_speed

system:
  name: System
  entities:
    - sensor.memory_use_percent
    - sensor.swap_use_percent
    - sensor.load_5m
    - sensor.processor_use
    - sensor.network_in
    - sensor.network_out
    - sensor.since_last_boot

dashboards:
  name: Dashboards
  entities:
    - switch.dashboard_eg_screen
