- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: swap_use_percent
    - type: load_5m
    - type: processor_use
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: since_last_boot
